platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

project 'Empik Weather.xcodeproj'

target 'Empik Weather' do
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RealmSwift', '10.34.1'
  pod 'RxRealm', '5.0.4'
  pod 'Moya/RxSwift', '15.0.0'
  pod 'Alamofire', '5.6.4'
  pod 'SnapKit', '5.6.0'
end
